config/routes.rb
Shreefogify::Application.routes.draw do
  resources :explorers, :only => [:new, :create, :index]
  resources :authentications, :only => [:index, :create]
  resources :albums, :only => [:index]
  resources :friends, :only => [:index]
  resources :pictures
  resources :fb_logouts, :only => [:index]

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout'  }
  match 'auth/:provider/callback' => 'authentications#create'
  root :to => "authentications#index"
end

app/controllers/friends_controller.rb
class FriendsController < FbBaseController
  before_filter :authenticate_user!
  include FogifyHelper::GraphHelper  #graph helper defined here

  # GET /friends
  # GET /friends.json
  def index
    @fb_id, access_token =  get_fb_info()
    @graph = get_graph(access_token)

    if @graph.nil?
      redirect_to '/auth/facebook'
    else
      friends = Hash.new
      begin
        explorer = Explorer.find_by_explorer_id(@fb_id)
        friend_id = (explorer.nil?) ? nil : explorer.friend_id

        top_friends = get_top_friends_likes(@graph,friend_id)
        unless top_friends.nil?
          top_friends.each do |friend_hash|
            if friends[friend_hash['user_id']].nil?
              friends[friend_hash['user_id']] = 1
            else
              friends[friend_hash['user_id']] = friends[friend_hash['user_id']] + 1
            end
          end
          @hashAsArrays = friends.to_a  # converts into two dimensional array
          @hashAsArrays = @hashAsArrays.sort_by{|k,v| v} #sort by value
          @hashAsArrays = @hashAsArrays.reverse
          @names = get_basic_users_info(@graph, friends.keys)
          friends = nil
        end
        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @max_likes }
        end
      rescue => e
        @error_flag = true
      end
    end

  end

  # GET /friends/1
  # GET /friends/1.json
  def show
    @friend = Friend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @friend }
    end
  end

  # GET /friends/new
  # GET /friends/new.json
  def new
    @friend = Friend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @friend }
    end
  end

  # GET /friends/1/edit
  def edit
    @friend = Friend.find(params[:id])
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(params[:friend])

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render json: @friend, status: :created, location: @friend }
      else
        format.html { render action: "new" }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /friends/1
  # PUT /friends/1.json
  def update
    @friend = Friend.find(params[:id])

    respond_to do |format|
      if @friend.update_attributes(params[:friend])
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<% if ((@hashAsArrays.nil?) || (@hashAsArrays.length == 0) ||
        (@names.nil?) || (@names.length == 0) ) %>

<div class="row alert alert-block">
  <p class="text-info offset0">
    Unable to list friends by like count  !

  </p>
</div>
<% else %>
<h3> Top friends by Photo like count </h3>
<table class="table  table-striped">
<%
   i = 0

   @hashAsArrays.each do |key,value|
        user_hash = nil
        hash_index = @names[key.to_s]
        user_hash = hash_index[0] unless hash_index.blank?
        if hash_index.blank? || user_hash.blank?
            if ((i+=1) >= 6) # magic 6
              break
            else
              next
            end
        end
        break if ((i+=1) >= 6) # magic 6

%>
  <tr>
    <td> <%= image_tag(user_hash['pic_square']) %> </td>
    <td> <%= user_hash['name'] %> </td>
    <td> <%= value %> </td>
  </tr>
<% end %>
</table>
<%end %>
<br />

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>