config/routes.rb
Shreefogify::Application.routes.draw do
  resources :explorers, :only => [:new, :create, :index]
  resources :authentications, :only => [:index, :create]
  resources :albums, :only => [:index]
  resources :friends, :only => [:index]
  resources :pictures
  resources :fb_logouts, :only => [:index]

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout'  }
  match 'auth/:provider/callback' => 'authentications#create'
  root :to => "authentications#index"
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :album_id, :img_comment, :img_name, :image, :image_url
  belongs_to :album
end

app/controllers/pictures_controller.rb
class PicturesController < FbBaseController
  # GET /pictures
  # GET /pictures.json
  before_filter :authenticate_user!
  include FogifyHelper::GraphHelper  #graph helper defined here

  def index

    @fb_id, access_token =  get_fb_info()
    @graph = get_graph(access_token)
    @from = 0
    @to = DateTime.now().strftime("%s").to_i

    if @graph.nil?
      redirect_to '/auth/facebook'
    else
      begin
        explorer = Explorer.find_by_explorer_id(@fb_id)
        friend_id = (explorer.nil?) ? nil : explorer.friend_id

        from_dt = params['from']
        unless (from_dt.nil?)
          begin
            if (from_dt.length > 0)
              @from = Date.strptime(from_dt,'%m/%d/%Y').strftime("%s").to_i
            end
          rescue => e1
            #ignore block. @from defaults to beginning of epoc
          end
        end

        to_dt = params['to']
        unless (to_dt.nil?)
          begin
            if (to_dt.length > 0)
              @to = Date.strptime(to_dt,'%m/%d/%Y').strftime("%s").to_i
            end
          rescue => e1
            #ignore block. @to is defaults to now
          end
        end


        photo_info = get_photo_with_max_likes(@graph,friend_id,@from,@to)
        unless photo_info.nil?
          photo_id = photo_info[0]['object_id']
          #go graph route to avoid multiple FQL for maintainability
          @max_likes = @graph.get_object("#{photo_id}")
        end
        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @max_likes }
        end
      rescue => e
        @error_flag = true
      end
    end

  end


  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= form_for @picture, :html => {:multipart => true}  do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :album_id %><br />
    <%= f.number_field :album_id %>
  </div>
  <div class="field">
    <%= f.label :img_name %><br />
    <%= f.text_field :img_name %>
  </div>
   <p>
    <%= f.file_field :image %>
  </p>
  <div class="field">
    <%= f.label :img_comment %><br />
    <%= f.text_field :img_comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h3>Photos with most likes ! </h3>
<%= form_tag("/pictures", :method => "get") do %>
    <div class= "row">
      <div class="span9 offset0">
      <p class="text-info">
        Date filter is currently an experimental feature that allows to view most liked photos in a specific date range.
        Date input needs to be in the format of mm/dd/yyyy. In case of input format error, "from" defaults to epoch
        (beginning of time !) and "to" defaults to current date.
     </div>
      </div>
    <div class= "row">
      <div class="span2">
        <p> from: </p>
      </div>
      <div class="span2">
        <p> to: </p>
      </div>
    </div>
    <div class="row">
      <div class="span2">
        <input name="from" type="text" class="span2 input-small" placeholder="mm/dd/yyyy"/>
      </div>
      <div class="span2">
        <input name ="to" type="text" class="span2 input-small" placeholder="mm/dd/yyyy" />
      </div>
      <div class="span3">
        <%= submit_tag("Apply date filter",:class => "btn span2") %>
      </div>
    </div>
<% end %>

<%
   unless @max_likes.nil? || @max_likes['likes'].nil?
     all_likes = @max_likes['likes']['data']
 %>
    <div class='row'>
      <div class="span6">.
        <p>  <%=   link_to(image_tag(@max_likes['source']),@max_likes['link'], nil) %> </p>

      </div>
    </div>
<% else %>
    <div class="alert"> Unable to locate a photo with maximum likes ! </div>
<% end %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= stylesheet_link_tag "application" %>
  <b>Album:</b>
  <%= @picture.album_id %>
</p>

<p>
  <b>Img name:</b>
  <%= @picture.img_name %>
</p>

<%= image_tag @picture.image_url, :class => 'imgfms' %>


<p>
  <b>Img comment:</b>
  <%= @picture.img_comment %>
</p>


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>