config/routes.rb
Shreefogify::Application.routes.draw do
  resources :explorers, :only => [:new, :create, :index]
  resources :authentications, :only => [:index, :create]
  resources :albums, :only => [:index]
  resources :friends, :only => [:index]
  resources :pictures
  resources :fb_logouts, :only => [:index]

  devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout'  }
  match 'auth/:provider/callback' => 'authentications#create'
  root :to => "authentications#index"
end

app/controllers/fb_logouts_controller.rb
class FbLogoutsController < FbBaseController
  # GET /fb_logouts
  # GET /fb_logouts.json
  def index
    auth_rec = get_auth_rec
    unless auth_rec.nil?
      auth_rec.access_token = nil
      auth_rec.save
    end
    fb_id, access_token =  get_fb_info()
    explorer = Explorer.find_by_explorer_id(fb_id)
    unless explorer.nil?
      explorer.friend_id=nil
      explorer.save
    end

    redirect_to destroy_user_session_path

  end

  # GET /fb_logouts/1
  # GET /fb_logouts/1.json
  def show
    @fb_logout = FbLogout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fb_logout }
    end
  end

  # GET /fb_logouts/new
  # GET /fb_logouts/new.json
  def new
    @fb_logout = FbLogout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fb_logout }
    end
  end

  # GET /fb_logouts/1/edit
  def edit
    @fb_logout = FbLogout.find(params[:id])
  end

  # POST /fb_logouts
  # POST /fb_logouts.json
  def create
    @fb_logout = FbLogout.new(params[:fb_logout])

    respond_to do |format|
      if @fb_logout.save
        format.html { redirect_to @fb_logout, notice: 'Fb logout was successfully created.' }
        format.json { render json: @fb_logout, status: :created, location: @fb_logout }
      else
        format.html { render action: "new" }
        format.json { render json: @fb_logout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fb_logouts/1
  # PUT /fb_logouts/1.json
  def update
    @fb_logout = FbLogout.find(params[:id])

    respond_to do |format|
      if @fb_logout.update_attributes(params[:fb_logout])
        format.html { redirect_to @fb_logout, notice: 'Fb logout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fb_logout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fb_logouts/1
  # DELETE /fb_logouts/1.json
  def destroy
    @fb_logout = FbLogout.find(params[:id])
    @fb_logout.destroy

    respond_to do |format|
      format.html { redirect_to fb_logouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fb_logouts_helper.rb
module FbLogoutsHelper
end

app/views/fb_logouts/_form.html.erb
<%= form_for(@fb_logout) do |f| %>
  <% if @fb_logout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fb_logout.errors.count, "error") %> prohibited this fb_logout from being saved:</h2>

      <ul>
      <% @fb_logout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fb_logouts/edit.html.erb
<h1>Editing fb_logout</h1>

<%= render 'form' %>

<%= link_to 'Show', @fb_logout %> |
<%= link_to 'Back', fb_logouts_path %>

app/views/fb_logouts/index.html.erb
<h1>Listing fb_logouts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fb_logouts.each do |fb_logout| %>
  <tr>
    <td><%= link_to 'Show', fb_logout %></td>
    <td><%= link_to 'Edit', edit_fb_logout_path(fb_logout) %></td>
    <td><%= link_to 'Destroy', fb_logout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fb logout', new_fb_logout_path %>

app/views/fb_logouts/new.html.erb
<h1>New fb_logout</h1>

<%= render 'form' %>

<%= link_to 'Back', fb_logouts_path %>

app/views/fb_logouts/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_fb_logout_path(@fb_logout) %> |
<%= link_to 'Back', fb_logouts_path %>